// 备注类型的文件，用于辅助代码编写，不会被编译至项目中
// Generated by https://quicktype.io

export interface LessonArrayType {
  sid: string
  week: string
  orders: number
  cname: string
  signalordouble: string
  teach: string
  classroom: string
}
// Generated by https://quicktype.io

export interface BookType {
  bid: string
  name: string
  number: number
}

export interface ProjectMembers {
  sid: string
}
