// 备注类型的文件，用于辅助代码编写，不会被编译至项目中
// Generated by https://quicktype.io

export interface LessonArrayType {
  sid: string //用户账号id
  week: string //课程在周几
  orders: number //课程在当天的节次
  cname: string //课程名称
  signalordouble: string //单双周
  teach: string //教师姓名
  classroom: string //上课地点
}
// Generated by https://quicktype.io

export interface BookType {
  bid: string
  name: string
  number: number
}

export interface ProjectMembers {
  sid: string
}

export interface ContactType {
  sid: string //用户账号id
  name: string //用户账号姓名
  grade: string //就读年级
  tel: string //手机号码
  sex: string //性别
  cardid: string //身份证号
  bankcard: string //银行卡号
  kind: string //账户类型（普通账户、管理员）
  email: string //邮箱
  qq: string //QQ
  year: null //出生年月
}
